### ISSUE TITLE
[Issue] - Alignment issue

### ISSUE THREAD

**Issue by unappreciatedninja** [Vault-Defi/VaultDefi-NewSite#1]
**What page is the issue on:**
Homepage

**What needs to be changed/fixed/updated/etc**
The alignment of the videos to text is off. Videos seem higher

**Dark or Light mode:**
Both 

**Screenshots**
![Screenshot 2021-11-01 at 08 42 42](https://user-images.githubusercontent.com/93513127/139639473-a30d6e1f-ac20-4305-93a0-177fb38bc4a0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome Brave

**Smartphone (please complete the following information):**

(Click below to add a screenshot)

**Comment by gap579137** [comment]
So I offset them to try and add a little dimension but if you don't think it "works" I can align them. What do you think?

**Comment by unappreciatedninja** [comment]
Personally, I think that it would look better aligned. Here is a mock-up

![Screenshot_2021-11-01_at_10 29 22](https://user-images.githubusercontent.com/93513127/139651857-d56e7aa1-8b6e-4df0-8b8f-3465881d6b6c.png)

**Comment by gap579137** [comment]
I have pushed this see what you think

**Comment by unappreciatedninja** [comment]
I think it looks better now.
