### ISSUE TITLE
[Issue] - Big Donut

### ISSUE THREAD

**Issue by unappreciatedninja** [Vault-Defi/VaultDefi-NewSite#11]
The pie chart is huge and does not resize

**What page is the issue on:**
https://trusting-wozniak-ae5e67.netlify.app/safevault**What needs to be changed/fixed/updated/etc**

**Dark or Light mode:**
both 

**Screenshots**
![Screenshot 2021-11-10 at 09 16 50](https://user-images.githubusercontent.com/93513127/141075616-53d24700-5e58-4664-9011-2f560140872a.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Brave/chrome

**Smartphone (please complete the following information):**

(Click below to add a screenshot)

**Comment by gap579137** [comment]
This should be fixed please let me know
