### ISSUE TITLE
Bug on the glossary page

### ISSUE THREAD

**Issue by JoShkDev** [Vault-Defi/VaultDefi-NewSite#2]
![GlossaryBug](https://user-images.githubusercontent.com/59695997/139755242-577e6adc-2a05-4d18-95c9-17bc5f656694.JPG)

When you're on the glossary page there's a display problem with the nav menu

( https://trusting-wozniak-ae5e67.netlify.app/glossary )

**Comment by gap579137** [comment]
Thank you this has been fixed. Upload will be at 2100 CDT
