### ISSUE TITLE
Social medias missing

### ISSUE THREAD

**Issue by JoShkDev** [Vault-Defi/VaultDefi-NewSite#3]
![addallsocials](https://user-images.githubusercontent.com/59695997/139755402-73faf574-6d8a-48ae-995c-7e28d2dff977.JPG)

Hello, some social medias are missing 

here's the full list : 

https://twitter.com/VaultDeFi
https://www.youtube.com/c/VaultAcademy
https://www.facebook.com/VaultDefi
https://t.me/Vault_DeFi
https://www.reddit.com/r/Vault_DeFi/
https://discord.gg/vaultdefi

**Comment by gap579137** [comment]
Fixed, Thank you. Will be uploaded around 2100CDT
