### ISSUE TITLE
hover on nav buttons

### ISSUE THREAD

**Issue by JoShkDev** [Vault-Defi/VaultDefi-NewSite#6]
Do you plan to add an hover effect on those buttons ? 

![buttonsshouldhavehovereffect](https://user-images.githubusercontent.com/59695997/139755689-2f3a90f7-fa50-4c1f-a02c-47e42c9d4c14.JPG)

**Comment by gap579137** [comment]
Fixed, Thank you. Uploaded by 2100 CDT
