### ISSUE TITLE
[Issue] - Logos for SafeVault

### ISSUE THREAD

**Issue by unappreciatedninja** [Vault-Defi/VaultDefi-NewSite#8]
**What page is the issue on:**
https://trusting-wozniak-ae5e67.netlify.app/safevault

**What needs to be changed/fixed/updated/etc**
We need to choose the correct logo for tokens.
We have a mix of safevault with the rocket and safevault with the BUSD 

**Dark or Light mode:**
Both 

**Screenshots**
![Screenshot 2021-11-09 at 11 26 13](https://user-images.githubusercontent.com/93513127/140907597-fc264616-b57f-45a3-b427-97a2342981b4.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

(Click below to add a screenshot)

**Comment by gap579137** [comment]
Done
