### ISSUE TITLE
[Issue] - Trigger Your rewards

### ISSUE THREAD

**Issue by unappreciatedninja** [Vault-Defi/VaultDefi-NewSite#9]
**What page is the issue on:**
https://trusting-wozniak-ae5e67.netlify.app/safevault

**What needs to be changed/fixed/updated/etc**
TRIGGER YOUR REWARDS EARLY should be edited to use the dapp instead.
remove the waiting 24 hours, send 1 vault and explanation of the clock etc.. State rewards are automatic but then include a dapp link.  

**Dark or Light mode:**
Both 
![Screenshot 2021-11-09 at 11 28 02](https://user-images.githubusercontent.com/93513127/140908704-2f3a7321-5035-4c2f-a63a-3420a4c19b09.png)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

(Click below to add a screenshot)

**Comment by gap579137** [comment]
Done
